"""Best-known official URLs per resort id. The crawler verifies each one (name/alias must appear
in the page) and records renames/redirects. Several candidates may be given; the first that verifies wins."""

OFFICIAL = {
    1: ["https://www.sixsenses.com/en/resorts/laamu"],
    2: ["https://www.filitheyo.com/"],
    3: ["https://www.adaaran.com/selecthudhuranfushi/", "https://www.adaaran.com/"],
    4: ["https://www.ayadamaldives.com/"],
    5: ["https://www.ozenreservebolifushi.com/"],
    6: ["https://www.joalibeing.com/"],
    7: ["https://www.joali.com/"],
    8: ["https://www.hilton.com/en/hotels/mleamhi-hilton-maldives-amingiri-resort-and-spa/"],
    9: ["https://www.amilla.com/"],
    10: ["https://www.dreamlandmaldives.com/", "https://dreamland.com.mv/"],
    11: ["https://www.angaga.com.mv/", "https://angaga.com.mv/"],
    12: ["https://www.thulhagiri.com.mv/", "https://thulhagiri.com.mv/"],
    13: ["https://www.sandies-bathala.com/", "https://www.planhotel.com/en/hotel/sandies-bathala-maldives"],
    14: ["https://www.baglionihotels.com/category/baglioni-resort-maldives/", "https://www.baglionihotels.com/maldives/"],
    15: ["https://www.alilahotels.com/kothaifaru", "https://www.hyatt.com/alila/mleal-alila-kothaifaru-maldives"],
    16: ["https://www.marriott.com/en-us/hotels/mlejk-jw-marriott-kaafu-atoll-island-resort/overview/"],
    17: ["https://www.rihivelimaldives.com/", "https://rihiveli-maldives.com/"],
    18: ["https://www.marriott.com/en-us/hotels/mlejw-jw-marriott-maldives-resort-and-spa/overview/"],
    19: ["https://www.cenizaro.com/theresidence/maldives", "https://www.cenizaro.com/theresidence/maldives-falhumaafushi"],
    20: ["https://www.cenizaro.com/theresidence/maldives-dhigurah"],
    21: ["https://www.brennia.com/", "https://brenniakottefaru.com/"],
    22: ["https://www.melia.com/en/hotels/maldives/south-ari-atoll/melia-whale-lagoon-maldives", "https://www.barcelo.com/en-ww/barcelo-whale-lagoon-maldives/"],
    23: ["https://www.nooemaldives.com/"],
    24: ["https://www.canareef.com/"],
    25: ["https://www.halcyonmaldives.com/", "https://www.raffles.com/maldives/"],
    26: ["https://www.centarahotelsresorts.com/centara/crf/", "https://www.centarahotelsresorts.com/centara/crf"],
    27: ["https://www.parkhotelgroup.com/en/maldives", "https://www.parkhotelgroup.com/en/maldives/grand-park-kodhipparu"],
    28: ["https://www.kudadoo.com/"],
    29: ["https://www.jawakaraislands.com/"],
    30: ["https://www.hurawalhi.com/"],
    31: ["https://www.innahura.com/"],
    32: ["https://www.cocoonmaldives.com/"],
    33: ["https://www.dhigali.com/", "https://www.nivaresorts.com/dhigali"],
    34: ["https://www.adaaran.com/selectmeedhupparu/", "https://www.adaaran.com/"],
    35: ["https://www.heritancehotels.com/aarah/", "https://www.heritancehotels.com/aarah-maldives/"],
    36: ["https://www.coastlinemaldives.com/", "https://coastlineresidences.com/"],
    37: ["https://www.ritzcarlton.com/en/hotels/mlerz-the-ritz-carlton-maldives-fari-islands/overview/"],
    38: ["https://www.veligandu.com/"],
    39: ["https://www.nh-collection.com/en/hotel/nh-collection-maldives-havodda-resort", "https://www.nh-hotels.com/en/hotel/nh-collection-maldives-havodda-resort"],
    40: ["https://www.marriott.com/en-us/hotels/mlemd-le-meridien-maldives-resort-and-spa/overview/"],
    41: ["https://www.ozenlifemaadhoo.com/"],
    42: ["https://www.dhiggiri.com/", "https://dhiggiri.com/"],
    43: ["https://www.dhigufaru.com/"],
    44: ["https://www.hardrockhotels.com/maldives/", "https://hotel.hardrock.com/maldives/"],
    45: ["https://www.saiiresorts.com/maldives/lagoon/", "https://www.saiiresorts.com/"],
    46: ["https://www.so-maldives.com/", "https://www.so-hotels.com/en/maldives/"],
    47: ["https://www.hyatt.com/park-hyatt/en-US/mlemh-park-hyatt-maldives-hadahaa", "https://www.hyatt.com/en-US/hotel/maldives/park-hyatt-maldives-hadahaa/mlemh"],
    48: ["https://www.dusit.com/dusitthani-maldives/"],
    49: ["https://www.vakkarumaldives.com/"],
    50: ["https://www.sunsiyam.com/sun-siyam-olhuveli/"],
    51: ["https://www.emerald-maldives.com/"],
    52: ["https://www.erimaldives.com/", "https://www.eriyadu.com/"],
    53: ["https://www.cinnamonhotels.com/cinnamonhakuraahuraamaldives"],
    54: ["https://www.emerald-faarufushi.com/"],
    55: ["https://www.fihalhohi.com/", "https://www.fihalhohi.net/"],
    56: ["https://www.fourseasons.com/maldiveskh/"],
    57: ["https://www.fushifaru.com/"],
    58: ["https://www.fairmont-maldives.com/", "https://www.fairmont.com/maldives/"],
    59: ["https://www.jumeirah.com/en/stay/maldives/jumeirah-maldives-olhahali-island", "https://www.jumeirah.com/en/stay/maldives/jumeirah-maldives"],
    60: ["https://www.reethibeach.com/"],
    61: ["https://www.equatorvillage.com/", "https://equatorvillage.com.mv/"],
    62: ["https://www.coracoraresorts.com/"],
    63: ["https://www.hondaafushi.com/"],
    64: ["https://www.radissonhotels.com/en-us/hotels/radisson-blu-resort-maldives"],
    65: ["https://www.chevalblanc.com/en/maison/randheli/"],
    66: ["https://www.comohotels.com/maldives/como-maalifushi", "https://www.comohotels.com/maalifushi"],
    67: ["https://www.hilton.com/en/hotels/mlewawa-waldorf-astoria-maldives-ithaafushi/", "https://www.waldorfastoriamaldives.com/"],
    68: ["https://www.jaresortshotels.com/maldives/ja-manafaru", "https://www.jaresortshotels.com/maldives"],
    69: ["https://www.adaaran.com/clubrannalhi/", "https://www.adaaran.com/"],
    70: ["https://www.joyisland.com/", "https://joyislandmaldives.com/"],
    71: ["https://www.kagimaldives.com/"],
    72: ["https://www.embudu.com/"],
    73: ["https://www.summerislandmaldives.com/"],
    74: ["https://www.kandolhu.com/"],
    75: ["https://www.kandima.com/"],
    76: ["https://www.hideawaybeachmaldives.com/"],
    77: ["https://www.atmospherekanifushi.com/", "https://atmosphere-kanifushi.com/"],
    78: ["https://www.meeru.com/"],
    79: ["https://www.komandoo.com/"],
    80: ["https://www.raayamaldives.com/", "https://raaya-maldives.com/"],
    81: ["https://www.kuredu.com/"],
    82: ["https://www.ifuruisland.com/"],
    83: ["https://www.jawakaraislands.com/"],
    84: ["https://www.alimatharesort.com/", "https://www.alimatha.com/"],
    85: ["https://www.centarahotelsresorts.com/centara/cmlm/", "https://www.centarahotelsresorts.com/centaragrand/cglm/"],
    86: ["https://www.fourseasons.com/maldivesvoavah/"],
    87: ["https://www.fourseasons.com/maldiveslg/"],
    88: ["https://www.holidayinnresorts.com/kandooma", "https://www.ihg.com/holidayinnresorts/hotels/us/en/kandooma-maldives/mlemv/hoteldetail"],
    89: ["https://maldives.intercontinental.com/", "https://www.ihg.com/intercontinental/hotels/us/en/maamunagau/mlemr/hoteldetail"],
    90: ["https://www.sixsenses.com/en/resorts/kanuhura"],
    91: ["https://www.lilybeachmaldives.com/"],
    92: ["https://www.nh-hotels.com/en/hotel/nh-maldives-kuda-rah-resort", "https://www.amayaresorts.com/amayakudarah/"],
    93: ["https://www.maayafushi.com.mv/", "https://maayafushi.com/"],
    94: ["https://www.reethifaru.com/"],
    95: ["https://www.malahinikudabandos.com/"],
    96: ["https://www.banyantree.com/maldives/dhawa-ihuru", "https://www.dhawa.com/maldives/ihuru"],
    97: ["https://www.angsana.com/maldives/velavaru"],
    98: ["https://www.madifushiprivateisland.com/"],
    99: ["https://www.conradmaldives.com/", "https://www.hilton.com/en/hotels/mlehici-conrad-maldives-rangali-island/"],
    100: ["https://www.clubmed.com/r/kani/y", "https://www.clubmed.co.uk/r/kani/y"],
    101: ["https://www.clubmed.com/r/finolhu-villas/y", "https://www.clubmed.co.uk/r/finolhu-villas/y"],
    102: ["https://www.marriott.com/en-us/hotels/mlewh-w-maldives/overview/"],
    103: ["https://www.marriott.com/en-us/hotels/mlesi-sheraton-maldives-full-moon-resort-and-spa/overview/"],
    104: ["https://www.medhufushi.com/"],
    105: ["https://www.kudavillingili.com/"],
    106: ["https://www.anantara.com/en/kihavah-maldives"],
    107: ["https://www.marriott.com/en-us/hotels/mlewi-the-westin-maldives-miriandhoo-resort/overview/"],
    108: ["https://www.rahaaresort.com/", "https://rahaa.mv/"],
    109: ["https://www.constancehotels.com/en/hotels-resorts/maldives/moofushi/"],
    110: ["https://www.furaveri.com/"],
    111: ["https://www.huvafenfushi.com/"],
    112: ["https://www.nikaisland.com.mv/", "https://www.nikamaldives.com/"],
    113: ["https://all.accor.com/hotel/B1T5/index.en.shtml", "https://www.mercure-maldives-kooddoo.com/"],
    114: ["https://www.gangehi.com/"],
    115: ["https://www.obluselectsangeli.com/", "https://www.oblu-sangeli.com/"],
    116: ["https://www.nova-maldives.com/"],
    117: ["https://www.niyama.com/"],
    118: ["https://www.sunsiyam.com/sun-siyam-iru-veli/"],
    119: ["https://www.outrigger.com/hotels-resorts/maldives/outrigger-maldives-maafushivaru-resort"],
    120: ["https://www.bandosmaldives.com/"],
    121: ["https://www.comohotels.com/maldives/como-cocoa-island", "https://www.comohotels.com/cocoaisland"],
    122: ["https://www.avanihotels.com/en/fares-maldives"],
    123: ["https://www.pullmanmaldivesmaamutaa.com/", "https://all.accor.com/hotel/B4S4/index.en.shtml"],
    124: ["https://www.aanugandu.com/", "https://aanugandu.mv/"],
    125: ["https://www.gili-lankanfushi.com/"],
    126: ["https://www.centarahotelsresorts.com/centaragrand/cirm/"],
    127: ["https://www.oagaresorts.com/", "https://oaga.art/"],
    128: ["https://www.oneandonlyresorts.com/reethi-rah"],
    129: ["https://www.riu.com/en/hotel/maldives/dhaalu-atoll/hotel-riu-palace-maldivas/", "https://www.riu.com/en/hotel/maldives/dhaalu-atoll/hotel-riu-atoll/"],
    130: ["https://www.robinson.com/en/clubs/robinson-noonu", "https://www.robinson.com/de/clubs/robinson-noonu"],
    131: ["https://www.robinson.com/en/clubs/robinson-maldives", "https://www.robinson.com/de/clubs/robinson-maldives"],
    132: ["https://www.nokuhotels.com/maldives", "https://www.nokumaldives.com/"],
    133: ["https://www.oblunaturehelengeli.com/", "https://www.oblu-helengeli.com/"],
    134: ["https://www.marriott.com/en-us/hotels/mlexr-the-st-regis-maldives-vommuli-resort/overview/"],
    135: ["https://www.diamondsresorts.com/en/diamonds-thudufushi", "https://www.diamondsresorts.com/en/thudufushi"],
    136: ["https://www.finolhu.com/"],
    137: ["https://soneva.com/resorts/soneva-secret/", "https://soneva.com/"],
    138: ["https://www.varu-atmosphere.com/", "https://varumaldives.com/"],
    139: ["https://www.kudafushiresort.com/"],
    140: ["https://www.standardhotels.com/maldives/properties/huruvalhi"],
    141: ["https://soneva.com/resorts/soneva-fushi/"],
    142: ["https://www.safariislandresort.com/", "https://safari-island.com/"],
    143: ["https://soneva.com/resorts/soneva-jani/"],
    144: ["https://www.southpalmmaldives.com/", "https://southpalm.com.mv/"],
    145: ["https://www.anantara.com/en/dhigu-maldives"],
    146: ["https://www.anantara.com/en/veli-maldives", "https://www.naladhu.com/"],
    147: ["https://www.sunsiyam.com/sun-siyam-vilu-reef/"],
    148: ["https://www.sunsiyam.com/the-sun-siyam-iru-fushi/", "https://www.sunsiyam.com/sun-siyam-iru-fushi/"],
    149: ["https://www.biyadhoo.com/"],
    150: ["https://www.cococollection.com/en/bodu-hithi", "https://www.cococollection.com/bodu-hithi"],
    151: ["https://www.cococollection.com/en/dhuni-kolhu", "https://www.cococollection.com/dhuni-kolhu"],
    152: ["https://www.makunudu.com/"],
    153: ["https://www.tajhotels.com/en-in/hotels/taj-coral-reef-maldives", "https://www.tajhotels.com/en-in/taj/taj-coral-reef-maldives/"],
    154: ["https://www.tajhotels.com/en-in/hotels/taj-exotica-maldives", "https://www.tajhotels.com/en-in/taj/taj-exotica-maldives/"],
    155: ["https://www.constancehotels.com/en/hotels-resorts/maldives/halaveli/"],
    156: ["https://www.driftmaldives.com/", "https://drift-theluveliga.com/"],
    157: ["https://www.thenautilusmaldives.com/"],
    158: ["https://www.patinahotels.com/maldives", "https://www.patinahotels.com/maldives/"],
    159: ["https://www.cinnamonhotels.com/cinnamondhonvelimaldives"],
    160: ["https://www.cinnamonhotels.com/cinnamonvelifushimaldives"],
    161: ["https://www.cinnamonhotels.com/ellaidhoomaldivesbycinnamon"],
    162: ["https://www.crossroadsmaldives.com/", "https://www.crossroadsmaldives.com/the-marina"],
    163: ["https://www.adaaran.com/prestigevadoo/", "https://www.adaaran.com/"],
    164: ["https://www.baros.com/"],
    165: ["https://www.velassaru.com/", "https://www.nivaresorts.com/velassaru"],
    166: ["https://www.kuramathi.com/"],
    167: ["https://www.milaidhoo.com/"],
    168: ["https://www.youandmemaldives.com/"],
    169: ["https://www.banyantree.com/maldives/vabbinfaru"],
    170: ["https://www.cocogiri.com/", "https://cocogirimaldives.com/"],
    171: ["https://www.velaaprivateisland.com/"],
    172: ["https://www.mirihi.com/"],
    173: ["https://www.kurumba.com/"],
    174: ["https://www.vilamendhoo.com/"],
    175: ["https://www.villanautica.com/", "https://www.villaresorts.com/villa-nautica/"],
    176: ["https://www.villapark.com.mv/", "https://www.villaresorts.com/villa-park/"],
    177: ["https://www.royal-island.com/", "https://www.villaresorts.com/royal-island/"],
    178: ["https://www.diamondsresorts.com/en/diamonds-athuruga", "https://www.diamondsresorts.com/en/athuruga"],
    179: ["https://www.sunsiyam.com/siyam-world/"],
    180: ["https://www.luxresorts.com/en/maldives/hotel/luxsouthariatoll"],
    181: ["https://www.yashmaldives.com/", "https://yashnatureresort.com/"],
    182: ["https://www.kuredhivaru.com/", "https://www.movenpick.com/en/asia/maldives/kuredhivaru/"],
}

# Known/likely digital asset managers used by Maldives resorts & groups.
# The crawler logs any link to these hosts and tries to enumerate public PDFs there.
DAM_HOSTS = [
    "dash.app", "brightdam.com", "bright-interactive.com",   # Dash (Bright) e.g. Pulse Hotels, Villa Resorts
    "bfldr.com", "brandfolder.com",                             # Brandfolder (Constance)
    "bynder.com", "bynder.io", "getbynder.com",                 # Bynder (Six Senses, others)
    "canto.com", "canto.global", "cantoflight.com",
    "widen.net", "widencollective.com",
    "imagerelay.com", "filecamp.com", "cloudinary.com", "frontify.com", "mediavalet.com", "assetbank",
    "box.com", "dropbox.com", "drive.google.com", "docs.google.com", "sharepoint.com", "onedrive.live.com", "1drv.ms",
    "issuu.com", "yumpu.com", "fliphtml5.com", "flippingbook.com", "online.flippingbook.com", "publitas.com",
    "anyflip.com", "calameo.com", "scribd.com", "heyzine.com", "simplebooklet.com", "flipsnack.com", "joomag.com",
    "hotelresb2b.com", "fastbooking", "ameliahub", "crowdriff.com", "barberstock.com", "pixlee", "thirdlight.com",
    "cloudfront.net", "s3.amazonaws.com", "blob.core.windows.net", "storage.googleapis.com", "digitaloceanspaces.com",
    "imgix.net", "contentful.com", "ctfassets.net", "prismic.io", "sanity.io", "squarespace.com", "wixstatic.com",
    "hubspotusercontent", "hubspot.net", "hsforms", "mailchimp.com", "mcusercontent.com", "sendinblue", "brevo.com",
]

# Known group-level (multi-resort) sites worth crawling as brand hubs
GROUP_SITES = {
    "pulsehotels": ("https://www.pulsehotelsandresorts.com/", [75, 116, 157]),      # Kandima, Nova, The Nautilus
    "villaresorts": ("https://www.villaresorts.com/", [175, 176, 177]),           # Villa Nautica, Villa Park, Royal Island
    "atmospherecore": ("https://www.atmosphere-core.com/", [5, 41, 77, 80, 115, 133, 138]),
    "crownchampa": ("https://www.crownandchamparesorts.com/", [28, 30, 31, 71, 78, 79, 81, 38, 174, 172, 29, 83]),
    "sunsiyam": ("https://www.sunsiyam.com/", [50, 118, 147, 148, 179]),
    "cococollection": ("https://www.cococollection.com/", [150, 151]),
    "adaaran": ("https://www.adaaran.com/", [3, 34, 69, 163]),
    "cinnamon": ("https://www.cinnamonhotels.com/", [53, 159, 160, 161]),
    "soneva": ("https://soneva.com/", [137, 141, 143]),
    "universal": ("https://www.universalresorts.com/", [164, 173, 166, 165, 33]),
    "niva": ("https://www.nivaresorts.com/", [33, 165]),
    "diamonds": ("https://www.diamondsresorts.com/", [135, 178]),
    "emerald": ("https://www.emerald-collection.com/", [51, 54]),
    "constance": ("https://www.constancehotels.com/", [109, 155]),
    "banyantree": ("https://www.banyantree.com/", [96, 169, 97]),
    "cenizaro": ("https://www.cenizaro.com/", [19, 20]),
    "jawakara": ("https://www.jawakaraislands.com/", [29, 83]),
    "joali": ("https://www.joali.com/", [6, 7]),
    "lilyhotels": ("https://www.lilyhotels.com/", [91, 76]),
    "planhotel": ("https://www.planhotel.com/", [13, 135, 178]),
    "centara": ("https://www.centarahotelsresorts.com/", [26, 85, 126]),
}
